Repository Orcpub/orcpub, pull requests merged in 2019-03, with the labels that each got.

#91 Feature/subclass print
  resources/fillable-char-sheet-0-spells.pdf
  resources/fillable-char-sheet-1-spells.pdf
  resources/fillable-char-sheet-2-spells.pdf
  resources/fillable-char-sheet-3-spells.pdf
  resources/fillable-char-sheet-4-spells.pdf
  resources/fillable-char-sheet-5-spells.pdf
  resources/fillable-char-sheet-6-spells.pdf
  src/cljc/orcpub/pdf_spec.cljc
Labels: area/application, enhancement

#89 Add subclass to class string
  src/cljc/orcpub/pdf_spec.cljc
Labels: area/application, enhancement

#99 Fix features dropdowns
  resources/public/css/compiled/styles.css
  src/clj/orcpub/styles/core.clj
Labels: area/application, bug

#97 Updated internal name of burglars-pack
  src/cljc/orcpub/dnd/e5/char_decision_tree.cljc
  src/cljc/orcpub/dnd/e5/classes.cljc
  test/cljc/orcpub/entity/strict_test.clj
Labels: area/application, bug

#102 Fix Figwheel compilation error from empty orcpub.dnd.e5.templates.ua-base ns
  README.md
  src/cljc/orcpub/dnd/e5/templates/ua_base.cljc
Labels: area/application, area/documentation

#106 Fix linebreaks in feats
  src/clj/orcpub/styles/core.clj
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug

#105 Spell card add materials
  resources/public/image/orcpub-card-logo - original.png
  resources/public/image/orcpub-card-logo.jpg
  resources/public/image/orcpub-card-logo.png
  src/clj/orcpub/pdf.clj
Labels: area/application, enhancement

#122 Pretty print orcbrews
  src/cljs/orcpub/dnd/e5/events.cljs
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement
