Repository Orcpub/orcpub, pull requests merged in 2019-01, with the labels that each got.

#10 Deployment update
  deploy/nginx.conf
  docker-compose.yaml
  docker/datomic/README.md
  docker/orcpub/Dockerfile
Labels: area/deployment, bug

#11 Enable SSL
  .gitignore
  deploy/nginx.conf
  deploy/snakeoil.sh
  docker-compose.yaml
Labels: area/deployment, enhancement

#26 Modify project.clj to be lein 2.8 compatible
  docker/bootstrap/Dockerfile
  docker/bootstrap/README.md
  docker/datomic/Dockerfile
  docker/orcpub/Dockerfile
  project.clj
Labels: area/ci, area/deployment, enhancement

#46 Cleanup datomic image
  deploy/transactor.properties
  docker-compose.yaml
  docker/datomic/Dockerfile
Labels: area/ci, enhancement

#62 Fix snakeoil bat
  deploy/snakeoil.bat
Labels: area/application, bug, enhancement

#65 Fix user account black
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug

#67 Fix sorting mycontent
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement

#70 Fix missing monster Challenge Ratings
  src/cljs/orcpub/dnd/e5/spell_subs.cljs
Labels: area/application, bug
