Repository Orcpub/orcpub, pull requests merged in 2019-04, with the labels that each got.

#142 Monster Senses & Armor Notes
  resources/public/css/compiled/styles.css
  src/clj/orcpub/styles/core.clj
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement

#145 Capitalised and pluralized Eldritch Invocations in the My Content tab
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug

#149 Added a generic user agent to get images on PDF creation.
  src/clj/orcpub/pdf.clj
Labels: area/application, bug

#148 Reorder tabs on character builder
  src/cljs/orcpub/character_builder.cljs
Labels: area/application, enhancement

#154 Spelling Corrections
  src/cljc/orcpub/dnd/e5/options.cljc
  src/cljc/orcpub/dnd/e5/template.cljc
  src/cljs/orcpub/character_builder.cljs
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement

#156 Show spell components in character builder
  src/cljc/orcpub/dnd/e5/options.cljc
Labels: area/application, enhancement

#137 Class Description and Subclass Flavor "help" text editable
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement

#140 Updated README's non-Docker instructions again
  README.md
Labels: area/documentation

#168 Subclass-builder Sort Selection Type and Modifier Type by title alphabetically
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement
