Repository Orcpub/orcpub, pull requests merged in 2020-09, with the labels that each got.

#425 Linting
  .clj-kondo/config.edn
  .ebextensions/https-instance-securitygroup.config
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  project.clj
  src/clj/orcpub/db/schema.clj
  src/clj/orcpub/email.clj
  src/clj/orcpub/pdf.clj
  src/clj/orcpub/pedestal.clj
  src/clj/orcpub/routes.clj
  src/clj/orcpub/security.clj
  src/clj/orcpub/styles/core.clj
  src/clj/orcpub/system.clj
  src/cljc/orcpub/components.cljc
  src/cljc/orcpub/dice.cljc
  src/cljc/orcpub/dnd/e5/character/random.cljc
  src/cljc/orcpub/dnd/e5/classes.cljc
  src/cljc/orcpub/dnd/e5/magic_items.cljc
  src/cljc/orcpub/dnd/e5/options.cljc
  src/cljc/orcpub/dnd/e5/selections.cljc
  src/cljc/orcpub/dnd/e5/templates/scag.cljc
  src/cljc/orcpub/dnd/e5/templates/ua_feats.cljc
  src/cljc/orcpub/dnd/e5/templates/ua_race_feats.cljc
  src/cljc/orcpub/dnd/e5/templates/ua_revised_ranger.cljc
  src/cljc/orcpub/dnd/e5/templates/ua_skill_feats.cljc
  src/cljc/orcpub/dnd/e5/templates/ua_warlock_and_wizard.cljc
  src/cljc/orcpub/dnd/e5/views_2.cljc
  src/cljc/orcpub/entity.cljc
  src/cljc/orcpub/route_map.cljc
  src/cljs/orcpub/character_builder.cljs
  src/cljs/orcpub/dnd/e5/db.cljs
  src/cljs/orcpub/dnd/e5/equipment_subs.cljs
  src/cljs/orcpub/dnd/e5/events.cljs
  src/cljs/orcpub/dnd/e5/spell_subs.cljs
  src/cljs/orcpub/dnd/e5/subs.cljs
  src/cljs/orcpub/dnd/e5/views.cljs
  test/clj/orcpub/routes_test.clj
  web/cljs/orcpub/core.cljs
Labels: area/application, area/ci, area/deployment, enhancement

#432 Upgrade FontAwesome
  .gitignore
  project.clj
  resources/public/font-awesome-4.7.0/HELP-US-OUT.txt
  resources/public/font-awesome-4.7.0/css/font-awesome.css
  resources/public/font-awesome-4.7.0/css/font-awesome.min.css
  resources/public/font-awesome-4.7.0/fonts/FontAwesome.otf
  resources/public/font-awesome-4.7.0/fonts/fontawesome-webfont.eot
  resources/public/font-awesome-4.7.0/fonts/fontawesome-webfont.svg
  resources/public/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf
  resources/public/font-awesome-4.7.0/fonts/fontawesome-webfont.woff
  resources/public/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2
  resources/public/font-awesome-4.7.0/less/animated.less
  resources/public/font-awesome-4.7.0/less/bordered-pulled.less
  resources/public/font-awesome-4.7.0/less/core.less
  resources/public/font-awesome-4.7.0/less/fixed-width.less
  resources/public/font-awesome-4.7.0/less/font-awesome.less
  resources/public/font-awesome-4.7.0/less/icons.less
  resources/public/font-awesome-4.7.0/less/larger.less
  resources/public/font-awesome-4.7.0/less/list.less
  resources/public/font-awesome-4.7.0/less/mixins.less
  resources/public/font-awesome-4.7.0/less/path.less
  resources/public/font-awesome-4.7.0/less/rotated-flipped.less
  resources/public/font-awesome-4.7.0/less/screen-reader.less
  resources/public/font-awesome-4.7.0/less/stacked.less
  resources/public/font-awesome-4.7.0/less/variables.less
  resources/public/font-awesome-4.7.0/scss/_animated.scss
  resources/public/font-awesome-4.7.0/scss/_bordered-pulled.scss
  resources/public/font-awesome-4.7.0/scss/_core.scss
  resources/public/font-awesome-4.7.0/scss/_fixed-width.scss
  resources/public/font-awesome-4.7.0/scss/_icons.scss
  resources/public/font-awesome-4.7.0/scss/_larger.scss
  resources/public/font-awesome-4.7.0/scss/_list.scss
  resources/public/font-awesome-4.7.0/scss/_mixins.scss
  resources/public/font-awesome-4.7.0/scss/_path.scss
  resources/public/font-awesome-4.7.0/scss/_rotated-flipped.scss
  resources/public/font-awesome-4.7.0/scss/_screen-reader.scss
  resources/public/font-awesome-4.7.0/scss/_stacked.scss
  resources/public/font-awesome-4.7.0/scss/_variables.scss
  resources/public/font-awesome-4.7.0/scss/font-awesome.scss
  src/clj/orcpub/index.clj
  src/clj/orcpub/routes.clj
  src/clj/orcpub/system.clj
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, area/ci, enhancement

#456 Added EMAIL_FROM_ADDRESS environment variable.
  README.md
  docker-compose-build.yaml
  docker-compose.yaml
  src/clj/orcpub/email.clj
Labels: area/application, enhancement

#458 Fix Imprisonment Spell Format issue.
  src/cljc/orcpub/dnd/e5/spells.cljc
Labels: area/application, bug

#450 Adds new character sheet - Alternate version
  resources/fillable-char-sheetstyle-1-0-spells.pdf
  resources/fillable-char-sheetstyle-1-1-spells.pdf
  resources/fillable-char-sheetstyle-1-2-spells.pdf
  resources/fillable-char-sheetstyle-1-3-spells.pdf
  resources/fillable-char-sheetstyle-1-4-spells.pdf
  resources/fillable-char-sheetstyle-1-5-spells.pdf
  resources/fillable-char-sheetstyle-1-6-spells.pdf
  resources/fillable-char-sheetstyle-2-0-spells.pdf
  resources/fillable-char-sheetstyle-2-1-spells.pdf
  resources/fillable-char-sheetstyle-2-2-spells.pdf
  resources/fillable-char-sheetstyle-2-3-spells.pdf
  resources/fillable-char-sheetstyle-2-4-spells.pdf
  resources/fillable-char-sheetstyle-2-5-spells.pdf
  resources/fillable-char-sheetstyle-2-6-spells.pdf
  src/clj/orcpub/routes.clj
  src/clj/orcpub/styles/core.clj
  src/cljc/orcpub/pdf_spec.cljc
  src/cljs/orcpub/dnd/e5/events.cljs
  src/cljs/orcpub/dnd/e5/subs.cljs
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, area/pdf, enhancement

#436 Implement roll buttons to be more compact
  src/clj/orcpub/styles/core.clj
  src/cljc/orcpub/dnd/e5/display.cljc
  src/cljs/orcpub/dnd/e5/views.cljs
  test/clj/orcpub/pdf_test.clj
Labels: area/application, enhancement
