Repository Orcpub/orcpub, pull requests merged in 2020-03, with the labels that each got.

#326 Removed Banner and links.
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application

#325 Remove Google and Facebook Auth API's
  project.clj
  resources/public/blank.html
  resources/public/css/compiled/styles.css
  resources/public/index.html
  src/clj/orcpub/index.clj
  src/clj/orcpub/oauth.clj
  src/clj/orcpub/privacy.clj
  src/clj/orcpub/routes.clj
  src/cljc/orcpub/dnd/e5/views_2.cljc
  src/cljc/orcpub/errors.cljc
  src/cljc/orcpub/route_map.cljc
  src/cljs/orcpub/character_builder.cljs
  src/cljs/orcpub/dnd/e5/events.cljs
  src/cljs/orcpub/dnd/e5/subs.cljs
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug, enhancement

#333 Update default value - Registration form set "Yes! Send me updates about orcpub" = false
  src/cljs/orcpub/dnd/e5/db.cljs
Labels: area/application

#329 Version bump Datomic from 0.9.5561 to 0.9.5703
  docker-compose-build.yaml
  docker-compose.yaml
  docker/datomic/Dockerfile
  project.clj
  src/clj/orcpub/system.clj
Labels: area/application

#343 Fix ritual on spell page
  src/clj/orcpub/pdf.clj
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug

#344 Fix for Sun Blade
  src/cljc/orcpub/dnd/e5/magic_items.cljc
  src/cljc/orcpub/dnd/e5/weapons.cljc
Labels: area/application, bug

#336 Update site look/feel - new header, new login sidebar
  env/dev/env/index.cljs
  native/cljs/orcpub/core.cljs
  resources/public/favicon/browserconfig.xml
  resources/public/favicon/favicon-114.png
  resources/public/favicon/favicon-120.png
  resources/public/favicon/favicon-144.png
  resources/public/favicon/favicon-150.png
  resources/public/favicon/favicon-152.png
  resources/public/favicon/favicon-16.png
  resources/public/favicon/favicon-160.png
  resources/public/favicon/favicon-180.png
  resources/public/favicon/favicon-192.png
  resources/public/favicon/favicon-310.png
  resources/public/favicon/favicon-32.png
  resources/public/favicon/favicon-57.png
  resources/public/favicon/favicon-60.png
  resources/public/favicon/favicon-64.png
  resources/public/favicon/favicon-70.png
  resources/public/favicon/favicon-72.png
  resources/public/favicon/favicon-76.png
  resources/public/favicon/favicon-96.png
  resources/public/favicon/favicon.ico
  resources/public/favicon/faviconit-instructions.txt
  resources/public/image/dmv-box-logo.png
  resources/public/image/dmv-logo.svg
  resources/public/image/header-background.jpg
  resources/public/image/login-side.jpg
  resources/public/image/orcpub-card-logo.png
  src/clj/orcpub/favicon.clj
  src/clj/orcpub/index.clj
  src/clj/orcpub/privacy.clj
  src/clj/orcpub/routes.clj
  src/cljc/orcpub/dnd/e5/views_2.cljc
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application

#342 Race Features Action Split
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, enhancement
