Repository Orcpub/orcpub, pull requests merged in 2020-01, with the labels that each got.

#297 Fixes #68 blank spells and duplicates
  src/cljc/orcpub/dnd/e5/spell_lists.cljc
Labels: bug

#287 Fix languages section in the subrace builder
  src/cljs/orcpub/dnd/e5/views.cljs
Labels: area/application, bug

#290 Applied align left to all spell slot fields
  resources/fillable-char-sheet-1-spells.pdf
  resources/fillable-char-sheet-2-spells.pdf
  resources/fillable-char-sheet-3-spells.pdf
  resources/fillable-char-sheet-4-spells.pdf
  resources/fillable-char-sheet-5-spells.pdf
  resources/fillable-char-sheet-6-spells.pdf
Labels: area/application, area/pdf
